# -*- coding: utf-8 -*-
"""Machine Learning model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dAOgch2KIJ3_nBBvpcTMtmiz1qn0k9B
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix,
    ConfusionMatrixDisplay, f1_score
)
from sklearn.utils.class_weight import compute_class_weight
from imblearn.over_sampling import SMOTE

# ==========================================================================
# PHASE 1: DATA PREPROCESSING & FEATURE ENGINEERING
# ==========================================================================
print("=" * 60)
print("  PHASE 1: Data Preprocessing & Feature Engineering")
print("=" * 60)

df = pd.read_csv('/content/sample_data/student_spending(1).csv')

if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)

print(f"✅ Dataset dimuat: {df.shape[0]} baris, {df.shape[1]} kolom")

# ------------------------------------------------------------------
# 1A. Feature Engineering
# ------------------------------------------------------------------
spending_cols = [
    'housing', 'food', 'transportation', 'books_supplies',
    'entertainment', 'personal_care', 'technology',
    'health_wellness', 'miscellaneous'
]

df['Total_Income']   = df['monthly_income'] + df['financial_aid']
df['Total_Spending'] = df[spending_cols].sum(axis=1)
df['Total_Income']   = df['Total_Income'].replace(0, 1)
df['Balance_Ratio']  = (df['Total_Income'] - df['Total_Spending']) / df['Total_Income']

# Rasio pengeluaran per kategori terhadap income
df['Food_Ratio']          = df['food']           / df['Total_Income']
df['Housing_Ratio']       = df['housing']        / df['Total_Income']
df['Entertainment_Ratio'] = df['entertainment']  / df['Total_Income']
df['Books_Ratio']         = df['books_supplies'] / df['Total_Income']

# ------------------------------------------------------------------
# 1B. Labeling Logic — threshold diturunkan agar Safe lebih banyak
# ------------------------------------------------------------------
# [PERBAIKAN UTAMA] Root cause Safe collapse:
#   Safe > 0.25 → hanya ~6% dari data → 12 sampel di test set
#   Solusi: turunkan threshold Safe ke 0.15
#
#   Safe    : ratio > 0.15  (masih simpan >15% income)
#   Warning : 0.00 – 0.15  (impas atau hemat sedikit)
#   Crisis  : ratio <  0.00 (pengeluaran melebihi income)

print("\n📊 Statistik Balance_Ratio:")
print(df['Balance_Ratio'].describe())

def assign_label(ratio):
    if ratio > 0.15:
        return 'Safe'
    elif ratio >= 0.00:
        return 'Warning'
    else:
        return 'Crisis'

df['Financial_Status'] = df['Balance_Ratio'].apply(assign_label)

print("\n📊 Distribusi Label:")
dist = df['Financial_Status'].value_counts()
print(dist)
print(f"\n   Crisis  : {dist.get('Crisis',  0) / len(df) * 100:.1f}%")
print(f"   Warning : {dist.get('Warning', 0) / len(df) * 100:.1f}%")
print(f"   Safe    : {dist.get('Safe',    0) / len(df) * 100:.1f}%")

# Auto-fallback jika Safe masih < 10%
if dist.get('Safe', 0) / len(df) < 0.10:
    print("\n⚠️  Safe masih < 10%, turunkan threshold ke 0.10...")
    def assign_label(ratio):
        if ratio > 0.10:
            return 'Safe'
        elif ratio >= 0.00:
            return 'Warning'
        else:
            return 'Crisis'
    df['Financial_Status'] = df['Balance_Ratio'].apply(assign_label)
    dist = df['Financial_Status'].value_counts()
    print("📊 Distribusi Label (revised):")
    print(dist)

# ------------------------------------------------------------------
# 1C. Income Bracket & Encoding
# ------------------------------------------------------------------
df['Income_Bracket'] = pd.qcut(df['Total_Income'], q=10, labels=False)

categorical_cols = ['gender', 'year_in_school', 'major', 'preferred_payment_method']
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

X = df_encoded.drop(columns=[
    'Total_Income', 'Total_Spending', 'Balance_Ratio', 'Financial_Status',
    'tuition', 'monthly_income', 'financial_aid'
])
y = df_encoded['Financial_Status']

print(f"\n✅ Total fitur setelah encoding: {X.shape[1]}")

# ------------------------------------------------------------------
# 1D. Train-Test Split (Stratified)
# ------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\n📦 Train: {X_train.shape[0]} sampel | Test: {X_test.shape[0]} sampel")
print("\nDistribusi y_train:")
print(y_train.value_counts())
print("\nDistribusi y_test:")
print(y_test.value_counts())


# ==========================================================================
# PHASE 2: SMOTE — OVERSAMPLING HANYA PADA TRAINING SET
# ==========================================================================
print("\n" + "=" * 60)
print("  PHASE 2: SMOTE - Oversampling Training Set")
print("=" * 60)

# k_neighbors dari kelas paling minoritas di train
min_class_count = y_train.value_counts().min()
k_neighbors     = max(1, min(5, min_class_count - 1))

print(f"   Kelas paling minoritas: {min_class_count} sampel → k_neighbors={k_neighbors}")

smote = SMOTE(random_state=42, k_neighbors=k_neighbors)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("✅ Distribusi y_train SETELAH SMOTE:")
print(pd.Series(y_train_res).value_counts())


# ==========================================================================
# PHASE 3: MODEL TRAINING
# ==========================================================================
print("\n" + "=" * 60)
print("  PHASE 3: Model Training")
print("=" * 60)

# ------------------------------------------------------------------
# 3A. Baseline: Logistic Regression
# ------------------------------------------------------------------
print("\n[Baseline] Training Logistic Regression...")

logreg = LogisticRegression(max_iter=2000, class_weight='balanced', random_state=42)
logreg.fit(X_train_res, y_train_res)
y_pred_logreg = logreg.predict(X_test)

print("✅ Logistic Regression selesai.")

# ------------------------------------------------------------------
# 3B. Manual class_weight — Boost Safe DAN Warning
# ------------------------------------------------------------------
# [PERBAIKAN] Safe di-boost 2x agar model lebih sensitif mendeteksinya
classes = np.unique(y_train)
weights = compute_class_weight('balanced', classes=classes, y=y_train)
class_weight_dict = dict(zip(classes, weights))

class_weight_dict['Warning'] *= 1.5
class_weight_dict['Safe']    *= 2.0   # boost lebih agresif untuk Safe

print(f"\n⚖️  Class weights (dengan boost):")
for cls, w in sorted(class_weight_dict.items()):
    print(f"   {cls}: {w:.4f}")

# ------------------------------------------------------------------
# 3C. Random Forest + GridSearchCV
# ------------------------------------------------------------------
print("\n[Primary] Hyperparameter Tuning Random Forest (GridSearchCV)...")

rf_base = RandomForestClassifier(random_state=42, class_weight=class_weight_dict)

param_grid = {
    'n_estimators'     : [200, 300, 400],
    'max_depth'        : [10, 15, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf' : [1, 2],
    'max_features'     : ['sqrt', 'log2']
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid_search = GridSearchCV(
    estimator=rf_base,
    param_grid=param_grid,
    cv=cv,
    scoring='f1_macro',
    n_jobs=-1,
    verbose=1
)
grid_search.fit(X_train_res, y_train_res)

best_rf = grid_search.best_estimator_

print(f"\n✅ Best params  : {grid_search.best_params_}")
print(f"   Best CV F1   : {grid_search.best_score_:.4f}")


# ==========================================================================
# PHASE 4: EVALUASI MODEL
# ==========================================================================
print("\n" + "=" * 60)
print("  PHASE 4: Evaluasi Model")
print("=" * 60)

# ------------------------------------------------------------------
# 4A. Prediksi Standar
# ------------------------------------------------------------------
y_pred_rf = best_rf.predict(X_test)

print("\n[Baseline] Logistic Regression Report:")
print(classification_report(y_test, y_pred_logreg, zero_division=0))

print("\n[Primary] Random Forest Report (Standard Threshold):")
print(classification_report(y_test, y_pred_rf, zero_division=0))

# ------------------------------------------------------------------
# 4B. Multi-Class Threshold Tuning
# ------------------------------------------------------------------
# Sweep Warning & Safe threshold bersamaan.
# Constraint: semua kelas F1 >= MIN_F1 (tidak ada yang collapse).

y_prob       = best_rf.predict_proba(X_test)
class_labels = list(best_rf.classes_)
warning_idx  = class_labels.index('Warning')
safe_idx     = class_labels.index('Safe')

print("\n🔍 Mencari threshold optimal (multi-class, semua kelas dijaga)...")

best_score       = 0.0
best_thr_warn    = 0.33
best_thr_safe    = 0.33
MIN_F1_PER_CLASS = 0.30

for thr_warn in np.arange(0.15, 0.55, 0.02):
    for thr_safe in np.arange(0.10, 0.55, 0.02):
        y_pred_thr = []
        for probs in y_prob:
            candidates = {}
            if probs[warning_idx] >= thr_warn:
                candidates['Warning'] = probs[warning_idx]
            if probs[safe_idx] >= thr_safe:
                candidates['Safe'] = probs[safe_idx]
            if candidates:
                y_pred_thr.append(max(candidates, key=candidates.get))
            else:
                y_pred_thr.append(class_labels[np.argmax(probs)])

        report = classification_report(
            y_test, y_pred_thr, output_dict=True, zero_division=0
        )

        f1_crisis  = report.get('Crisis',  {}).get('f1-score', 0)
        f1_warning = report.get('Warning', {}).get('f1-score', 0)
        f1_safe    = report.get('Safe',    {}).get('f1-score', 0)

        if min(f1_crisis, f1_warning, f1_safe) < MIN_F1_PER_CLASS:
            continue

        macro_f1 = report['macro avg']['f1-score']
        if macro_f1 > best_score:
            best_score    = macro_f1
            best_thr_warn = thr_warn
            best_thr_safe = thr_safe

print(f"   ✅ Threshold Warning optimal : {best_thr_warn:.2f}")
print(f"   ✅ Threshold Safe optimal    : {best_thr_safe:.2f}")
print(f"   ✅ Best Macro F1             : {best_score:.4f}")

# Prediksi final
y_pred_tuned = []
for probs in y_prob:
    candidates = {}
    if probs[warning_idx] >= best_thr_warn:
        candidates['Warning'] = probs[warning_idx]
    if probs[safe_idx] >= best_thr_safe:
        candidates['Safe'] = probs[safe_idx]
    if candidates:
        y_pred_tuned.append(max(candidates, key=candidates.get))
    else:
        y_pred_tuned.append(class_labels[np.argmax(probs)])

print("\n[Primary] Random Forest Report (Multi-Class Tuned Threshold):")
print(classification_report(y_test, y_pred_tuned, zero_division=0))

# ------------------------------------------------------------------
# 4C. Top 5 Feature Importance
# ------------------------------------------------------------------
feature_imp = pd.Series(best_rf.feature_importances_, index=X_train.columns)

print("\n🔥 Top 5 Variabel Pemicu Risiko Finansial:")
print(feature_imp.sort_values(ascending=False).head(5))

# ------------------------------------------------------------------
# 4D. Visualisasi
# ------------------------------------------------------------------
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Student Financial Health — Model Evaluation', fontsize=16, fontweight='bold')

# Plot 1: Distribusi Label
ax1 = axes[0, 0]
colors_map   = {'Crisis': '#e74c3c', 'Warning': '#f39c12', 'Safe': '#2ecc71'}
label_counts = df['Financial_Status'].value_counts()
bars = ax1.bar(
    label_counts.index, label_counts.values,
    color=[colors_map[l] for l in label_counts.index],
    edgecolor='black', linewidth=0.8
)
for bar, val in zip(bars, label_counts.values):
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 3,
             str(val), ha='center', va='bottom', fontweight='bold')
ax1.set_title('Distribusi Label', fontweight='bold')
ax1.set_ylabel('Jumlah Sampel')
ax1.set_xlabel('Status Finansial')

# Plot 2: Confusion Matrix (Tuned)
ax2 = axes[0, 1]
cm   = confusion_matrix(y_test, y_pred_tuned, labels=['Crisis', 'Warning', 'Safe'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Crisis', 'Warning', 'Safe'])
disp.plot(ax=ax2, colorbar=False, cmap='Blues')
ax2.set_title('Confusion Matrix (RF Tuned Threshold)', fontweight='bold')

# Plot 3: Top 10 Feature Importance
ax3 = axes[1, 0]
top10 = feature_imp.sort_values(ascending=False).head(10)
bar_colors = ['#e74c3c'] + ['#3498db'] * 9
top10[::-1].plot(kind='barh', ax=ax3, color=bar_colors[::-1], edgecolor='black', linewidth=0.5)
ax3.set_title('Top 10 Feature Importance', fontweight='bold')
ax3.set_xlabel('Importance Score')

# Plot 4: F1-Score Comparison per Kelas
ax4 = axes[1, 1]
report_lr     = classification_report(y_test, y_pred_logreg, output_dict=True, zero_division=0)
report_rf_std = classification_report(y_test, y_pred_rf,     output_dict=True, zero_division=0)
report_rf_tun = classification_report(y_test, y_pred_tuned,  output_dict=True, zero_division=0)

classes_plot = ['Crisis', 'Warning', 'Safe']
x     = np.arange(len(classes_plot))
width = 0.25

for i, (lbl, rpt) in enumerate([
    ('Logistic Reg', report_lr),
    ('RF Standard',  report_rf_std),
    ('RF Tuned',     report_rf_tun),
]):
    f1s = [rpt[c]['f1-score'] for c in classes_plot]
    ax4.bar(x + i * width, f1s, width, label=lbl, edgecolor='black', linewidth=0.5)

ax4.set_title('Perbandingan F1-Score per Kelas', fontweight='bold')
ax4.set_ylabel('F1-Score')
ax4.set_xticks(x + width)
ax4.set_xticklabels(classes_plot)
ax4.set_ylim(0, 1.1)
ax4.axhline(y=0.6, color='red', linestyle='--', alpha=0.5, linewidth=1)
ax4.legend()

plt.tight_layout()
plt.savefig('/content/model_evaluation.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ Visualisasi disimpan ke /content/model_evaluation.png")

# ------------------------------------------------------------------
# 4E. Simpan Model
# ------------------------------------------------------------------
joblib.dump(best_rf,               '/content/rf_financial_model.pkl')
joblib.dump(list(X_train.columns), '/content/model_columns.pkl')
joblib.dump({'warning': best_thr_warn, 'safe': best_thr_safe}, '/content/thresholds.pkl')
joblib.dump(class_labels,          '/content/class_labels.pkl')

print("\n✅ Model tersimpan:")
print("   /content/rf_financial_model.pkl")
print("   /content/model_columns.pkl")
print("   /content/thresholds.pkl  ← {'warning': X, 'safe': Y}")
print("   /content/class_labels.pkl")


"""
==========================================================================
  Student Financial Health Decision Support System
  Group 3 — Streamlit UI  (Rupiah Edition)

  Jalankan dengan: streamlit run app.py
==========================================================================
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import joblib

# ==========================================================================
# KONVERSI & FORMAT RUPIAH
# ==========================================================================
# Semua nilai slider dalam Rupiah (IDR).
# Model dilatih dengan data USD, jadi input di-scale ke USD sebelum prediksi.
USD_TO_IDR = 16_000

def to_usd(rp: int) -> float:
    return rp / USD_TO_IDR

def fmt_rp(val: int) -> str:
    """Format angka ke Rp xxx.xxx"""
    return f"Rp {val:,.0f}".replace(",", ".")

# ==========================================================================
# PAGE CONFIG
# ==========================================================================
st.set_page_config(
    page_title="AntiKanker (Anti Kantong Kering)",
    page_icon="💰",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ==========================================================================
# CUSTOM CSS
# ==========================================================================
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:ital,wght@0,300;0,400;0,500;1,300&display=swap');

:root {
    --crisis:  #FF4757;
    --warning: #FFA502;
    --safe:    #2ED573;
    --bg:      #0D0F14;
    --surface: #161921;
    --surface2:#1E2330;
    --border:  #2A2F3E;
    --text:    #E8EAF0;
    --muted:   #6B7280;
    --accent:  #4ECDC4;
}

html, body, [class*="css"] {
    font-family: 'DM Sans', sans-serif;
    background-color: var(--bg) !important;
    color: var(--text) !important;
}

/* Hide Streamlit chrome */
#MainMenu, footer, header { visibility: hidden; }
.block-container { padding: 2rem 2.5rem !important; max-width: 1400px; }

h1, h2, h3, h4 { font-family: 'Syne', sans-serif !important; }

[data-testid="stSidebar"] {
    background: var(--surface) !important;
    border-right: 1px solid var(--border) !important;
}
[data-testid="stSidebar"] * { color: var(--text) !important; }

[data-testid="stSlider"] > div > div > div > div {
    background: var(--accent) !important;
}

.stButton > button {
    font-family: 'Syne', sans-serif !important;
    font-weight: 700 !important;
    font-size: 1rem !important;
    letter-spacing: 0.05em !important;
    background: var(--accent) !important;
    color: #0D0F14 !important;
    border: none !important;
    border-radius: 8px !important;
    padding: 0.75rem 2rem !important;
    width: 100% !important;
    transition: opacity 0.2s !important;
}
.stButton > button:hover { opacity: 0.85 !important; }

[data-testid="metric-container"] {
    background: var(--surface2) !important;
    border: 1px solid var(--border) !important;
    border-radius: 12px !important;
    padding: 1rem !important;
}

[data-testid="stSelectbox"] > div,
[data-testid="stNumberInput"] > div { color: var(--text) !important; }

hr { border-color: var(--border) !important; }

.fin-card {
    background: var(--surface2);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 1.5rem;
    margin-bottom: 1rem;
}
.fin-card h4 {
    font-family: 'Syne', sans-serif;
    font-size: 0.75rem;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--muted);
    margin-bottom: 0.5rem;
}

.result-crisis  { border-left: 4px solid var(--crisis)  !important; }
.result-warning { border-left: 4px solid var(--warning) !important; }
.result-safe    { border-left: 4px solid var(--safe)    !important; }

.risk-bar-wrap { margin: 0.4rem 0; }
.risk-label { font-size: 0.82rem; color: var(--muted); margin-bottom: 2px; }
.risk-bar-bg {
    background: var(--border);
    border-radius: 4px;
    height: 8px;
    overflow: hidden;
}
.risk-bar-fill {
    height: 100%;
    border-radius: 4px;
    background: linear-gradient(90deg, var(--accent), #6C63FF);
    transition: width 0.6s ease;
}
</style>
""", unsafe_allow_html=True)


# ==========================================================================
# HELPERS
# ==========================================================================
MODEL_PATH     = 'rf_financial_model.pkl'
COLUMNS_PATH   = 'model_columns.pkl'
THRESHOLD_PATH = 'thresholds.pkl'
LABELS_PATH    = 'class_labels.pkl'

@st.cache_resource
def load_model():
    model        = joblib.load(MODEL_PATH)
    columns      = joblib.load(COLUMNS_PATH)
    thresholds   = joblib.load(THRESHOLD_PATH)
    class_labels = joblib.load(LABELS_PATH)
    return model, columns, thresholds, class_labels

def predict(input_dict_usd, model, columns, thresholds, class_labels):
    """Prediksi dengan multi-class threshold tuning (input sudah dalam USD)."""
    df_in = pd.DataFrame([input_dict_usd])
    df_in = pd.get_dummies(df_in)
    df_in = df_in.reindex(columns=columns, fill_value=0)

    probs       = model.predict_proba(df_in)[0]
    warning_idx = class_labels.index('Warning')
    safe_idx    = class_labels.index('Safe')

    thr_warn = thresholds.get('warning', 0.33)
    thr_safe = thresholds.get('safe',    0.33)

    candidates = {}
    if probs[warning_idx] >= thr_warn:
        candidates['Warning'] = probs[warning_idx]
    if probs[safe_idx] >= thr_safe:
        candidates['Safe'] = probs[safe_idx]

    status = max(candidates, key=candidates.get) if candidates \
             else class_labels[int(np.argmax(probs))]

    prob_dict  = dict(zip(class_labels, probs))
    feat_imp   = pd.Series(model.feature_importances_, index=columns)
    input_ser  = df_in.iloc[0]
    risk_score = (feat_imp * input_ser).sort_values(ascending=False)
    top_risks  = risk_score[risk_score > 0].head(5)

    return status, prob_dict, top_risks


STATUS_META = {
    'Crisis' : {'color': '#FF4757', 'emoji': '🚨',
                'msg': 'Pengeluaran melebihi pemasukan. Risiko kehabisan dana sangat tinggi.',
                'tips': ['Kurangi pengeluaran hiburan & personal care segera',
                         'Cari sumber pendapatan tambahan (part-time, freelance)',
                         'Hubungi konselor keuangan kampus',
                         'Buat anggaran ketat minggu ini']},
    'Warning': {'color': '#FFA502', 'emoji': '⚠️',
                'msg': 'Keuangan ketat. Masih aman tapi perlu penghematan segera.',
                'tips': ['Identifikasi 1–2 kategori pengeluaran terbesar dan kurangi 20%',
                         'Hindari pengeluaran impulsif selama 2 minggu ke depan',
                         'Pertimbangkan memasak sendiri daripada makan di luar',
                         'Pantau saldo setiap hari']},
    'Safe'   : {'color': '#2ED573', 'emoji': '✅',
                'msg': 'Kondisi finansial sehat. Tetap jaga pola pengeluaran ini.',
                'tips': ['Pertahankan rasio tabungan yang sudah baik',
                         'Pertimbangkan mulai dana darurat (3–6 bulan pengeluaran)',
                         'Evaluasi ulang setiap awal bulan',
                         'Manfaatkan sisa income untuk investasi kecil-kecilan']},
}


def make_spending_chart(spending_data_rp, income_rp):
    """Donut chart pengeluaran vs income (nilai dalam Rupiah)."""
    labels  = list(spending_data_rp.keys())
    values  = list(spending_data_rp.values())
    total_s = sum(values)
    saving  = max(0, income_rp - total_s)

    plot_labels = labels + (['Sisa'] if saving > 0 else [])
    plot_values = values + ([saving]  if saving > 0 else [])

    base_palette = ['#FF6B6B','#FFA502','#FFD93D','#6BCB77',
                    '#4D96FF','#C77DFF','#F72585','#4ECDC4','#2ED573']
    palette = (base_palette * 3)[:len(plot_labels)]

    fig, ax = plt.subplots(figsize=(5, 5), facecolor='#161921')
    wedges, texts, autotexts = ax.pie(
        plot_values,
        labels=None,
        autopct=lambda p: f'{p:.0f}%' if p > 4 else '',
        pctdistance=0.75,
        colors=palette,
        wedgeprops=dict(width=0.55, edgecolor='#161921', linewidth=2),
        startangle=90
    )
    for at in autotexts:
        at.set_color('white')
        at.set_fontsize(8)

    # Format Rupiah di tengah
    if total_s >= 1_000_000:
        center_txt = f"Rp {total_s/1_000_000:.1f}jt"
    else:
        center_txt = f"Rp {total_s:,.0f}".replace(",", ".")

    ax.text(0, 0.08, center_txt,
            ha='center', va='center', fontsize=10,
            fontweight='bold', color='white', fontfamily='sans-serif')
    ax.text(0, -0.18, 'Total Spending',
            ha='center', va='center', fontsize=7.5,
            color='#6B7280', fontfamily='sans-serif')

    legend_patches = [mpatches.Patch(color=palette[i], label=plot_labels[i])
                      for i in range(len(plot_labels))]
    ax.legend(handles=legend_patches, loc='lower center',
              bbox_to_anchor=(0.5, -0.22), ncol=3,
              fontsize=7, frameon=False, labelcolor='#9CA3AF')
    fig.tight_layout()
    return fig


def make_prob_chart(prob_dict):
    """Horizontal bar untuk probabilitas tiap kelas."""
    colors = {'Crisis': '#FF4757', 'Warning': '#FFA502', 'Safe': '#2ED573'}
    fig, ax = plt.subplots(figsize=(5, 2.2), facecolor='#161921')
    ax.set_facecolor('#161921')

    for i, (cls, prob) in enumerate(prob_dict.items()):
        ax.barh(cls, prob, color=colors.get(cls, '#4ECDC4'), height=0.5, edgecolor='none')
        ax.text(prob + 0.01, i, f'{prob:.1%}', va='center', fontsize=9, color='white')

    ax.set_xlim(0, 1.15)
    ax.set_xlabel('Probabilitas', color='#6B7280', fontsize=8)
    ax.tick_params(colors='#9CA3AF', labelsize=9)
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.axvline(x=0.33, color='#2A2F3E', linewidth=1, linestyle='--')
    fig.tight_layout()
    return fig


# ==========================================================================
# LOAD MODEL
# ==========================================================================
model_loaded = False
try:
    model, columns, thresholds, class_labels = load_model()
    model_loaded = True
except Exception as e:
    st.warning(f"⚠️ Model belum di-load. Jalankan training script terlebih dahulu.\n\nError: {e}")


# ==========================================================================
# HEADER
# ==========================================================================
st.markdown("""
<div style="padding: 2rem 0 1.5rem; border-bottom: 1px solid #2A2F3E; margin-bottom: 2rem;">
    <div style="display:flex; align-items:center; gap:1rem;">
        <div style="font-size:2.5rem;">💰</div>
        <div>
            <h1 style="margin:0; font-size:2rem; font-weight:800;
                       background: linear-gradient(135deg, #4ECDC4, #6C63FF);
                       -webkit-background-clip:text; -webkit-text-fill-color:transparent;">
                AntiKanker DSS
            </h1>
            <p style="margin:0; color:#6B7280; font-size:0.9rem; letter-spacing:0.05em;">
                Anti Kantong Kering · Student Financial Health Decision Support System
            </p>
        </div>
    </div>
</div>
""", unsafe_allow_html=True)


# ==========================================================================
# SIDEBAR — INPUT FORM
# ==========================================================================
with st.sidebar:
    st.markdown("""
    <div style="font-family:'Syne',sans-serif; font-size:1.1rem; font-weight:700;
                color:#E8EAF0; margin-bottom:1.5rem; padding-bottom:0.75rem;
                border-bottom:1px solid #2A2F3E;">
        📋 Input Data Mahasiswa
    </div>
    """, unsafe_allow_html=True)

    # ── Demografi ──
    st.markdown("**Demografi**")
    gender  = st.selectbox("Jenis Kelamin", ["Male", "Female"])
    year    = st.selectbox("Tahun Kuliah", ["Freshman", "Sophomore", "Junior", "Senior"])
    major   = st.selectbox("Jurusan", [
        "Engineering", "Business", "Computer Science",
        "Liberal Arts", "Biology", "Education",
        "Psychology", "Undeclared"
    ])
    payment = st.selectbox("Metode Pembayaran", [
        "Cash", "Credit/Debit Card", "Mobile Payment App"
    ])

    st.divider()

    # ── Pemasukan (Rupiah) ──
    st.markdown("**💵 Pemasukan Bulanan**")
    monthly_income_rp = st.slider("Uang Saku / Gaji (Rp)",
                                  0, 10_000_000, 3_000_000, 100_000,
                                  format="Rp %d")
    financial_aid_rp  = st.slider("Beasiswa / Bantuan (Rp)",
                                  0, 5_000_000, 500_000, 100_000,
                                  format="Rp %d")

    total_income_rp = monthly_income_rp + financial_aid_rp
    st.markdown(f"""
    <div style="background:#1E2330; border-radius:8px; padding:0.6rem 1rem;
                border:1px solid #2A2F3E; font-size:0.85rem; color:#4ECDC4;
                font-family:'Syne',sans-serif; font-weight:600; margin-top:0.5rem;">
        Total Pemasukan: {fmt_rp(total_income_rp)}
    </div>
    """, unsafe_allow_html=True)

    st.divider()

    # ── Pengeluaran (Rupiah) ──
    st.markdown("**🛒 Pengeluaran Bulanan**")

    spending_items_rp = {
        'housing'        : ("🏠 Kos / Kontrakan",      0, 3_000_000, 1_000_000, 50_000),
        'food'           : ("🍜 Makan & Minum",         0, 2_000_000,   600_000, 25_000),
        'transportation' : ("🚌 Transportasi",          0,   800_000,   200_000, 10_000),
        'books_supplies' : ("📚 Buku & ATK",            0,   500_000,   150_000, 10_000),
        'entertainment'  : ("🎮 Hiburan",               0, 1_000_000,   200_000, 10_000),
        'personal_care'  : ("💄 Perawatan Diri",        0,   600_000,   100_000, 10_000),
        'technology'     : ("💻 Teknologi & Pulsa",     0, 1_000_000,   150_000, 10_000),
        'health_wellness': ("🏋️ Kesehatan",             0,   600_000,   100_000, 10_000),
        'miscellaneous'  : ("📦 Lain-lain",             0,   800_000,   150_000, 10_000),
    }

    spending_vals_rp = {}
    for key, (label, mn, mx, default, step) in spending_items_rp.items():
        spending_vals_rp[key] = st.slider(label, mn, mx, default, step, format="Rp %d")

    total_spending_rp = sum(spending_vals_rp.values())
    balance_ratio     = (total_income_rp - total_spending_rp) / max(total_income_rp, 1)

    ratio_color = '#2ED573' if balance_ratio > 0.15 else ('#FFA502' if balance_ratio >= 0 else '#FF4757')
    st.markdown(f"""
    <div style="background:#1E2330; border-radius:8px; padding:0.6rem 1rem;
                border:1px solid #2A2F3E; font-size:0.85rem; margin-top:0.5rem;">
        <span style="color:#6B7280;">Total Pengeluaran: </span>
        <span style="color:white; font-weight:600;">{fmt_rp(total_spending_rp)}</span>
        <span style="color:#6B7280; margin-left:1rem;">Balance: </span>
        <span style="color:{ratio_color}; font-weight:600;">{balance_ratio:.1%}</span>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    predict_btn = st.button("🔍 Analisis Kesehatan Finansial")


# ==========================================================================
# MAIN CONTENT
# ==========================================================================
if not predict_btn:
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown("""
        <div class="fin-card">
            <h4>Langkah 1</h4>
            <div style="font-size:2rem; margin-bottom:0.5rem;">📋</div>
            <div style="font-weight:600; margin-bottom:0.4rem;">Isi Data</div>
            <div style="color:#6B7280; font-size:0.85rem;">
                Masukkan data demografi, pemasukan, dan estimasi pengeluaran bulanan di sidebar kiri.
            </div>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        st.markdown("""
        <div class="fin-card">
            <h4>Langkah 2</h4>
            <div style="font-size:2rem; margin-bottom:0.5rem;">🔍</div>
            <div style="font-weight:600; margin-bottom:0.4rem;">Analisis</div>
            <div style="color:#6B7280; font-size:0.85rem;">
                Klik tombol "Analisis" untuk menjalankan model Random Forest dan mendapatkan prediksi.
            </div>
        </div>
        """, unsafe_allow_html=True)
    with col3:
        st.markdown("""
        <div class="fin-card">
            <h4>Langkah 3</h4>
            <div style="font-size:2rem; margin-bottom:0.5rem;">💡</div>
            <div style="font-weight:600; margin-bottom:0.4rem;">Baca Rekomendasi</div>
            <div style="color:#6B7280; font-size:0.85rem;">
                Sistem akan menampilkan status, pemicu risiko, dan saran spesifik untuk kondisi keuanganmu.
            </div>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("""
    <div style="font-family:'Syne',sans-serif; font-size:0.75rem; font-weight:600;
                letter-spacing:0.12em; text-transform:uppercase; color:#6B7280;
                margin-bottom:1rem;">Kategori Status Finansial</div>
    """, unsafe_allow_html=True)

    c1, c2, c3 = st.columns(3)
    for col, (status, meta) in zip([c1, c2, c3], STATUS_META.items()):
        with col:
            st.markdown(f"""
            <div class="fin-card result-{status.lower()}">
                <div style="font-size:1.8rem; margin-bottom:0.5rem;">{meta['emoji']}</div>
                <div style="font-family:'Syne',sans-serif; font-size:1.1rem;
                            font-weight:700; color:{meta['color']}; margin-bottom:0.4rem;">
                    {status}
                </div>
                <div style="color:#6B7280; font-size:0.82rem;">{meta['msg']}</div>
            </div>
            """, unsafe_allow_html=True)

else:
    # ==========================================================================
    # HASIL PREDIKSI
    # ==========================================================================
    if not model_loaded:
        st.error("Model tidak tersedia. Jalankan training script terlebih dahulu.")
        st.stop()

    # Konversi Rupiah → USD sebelum masuk ke model
    spending_vals_usd = {k: to_usd(v) for k, v in spending_vals_rp.items()}
    monthly_income_usd = to_usd(monthly_income_rp)
    financial_aid_usd  = to_usd(financial_aid_rp)
    total_income_usd   = monthly_income_usd + financial_aid_usd

    input_dict_usd = {
        'monthly_income' : monthly_income_usd,
        'financial_aid'  : financial_aid_usd,
        'gender'         : gender,
        'year_in_school' : year,
        'major'          : major,
        'preferred_payment_method': payment,
        **spending_vals_usd,
        'Income_Bracket'     : 5,
        'Food_Ratio'         : spending_vals_usd['food']          / max(total_income_usd, 1),
        'Housing_Ratio'      : spending_vals_usd['housing']       / max(total_income_usd, 1),
        'Entertainment_Ratio': spending_vals_usd['entertainment'] / max(total_income_usd, 1),
        'Books_Ratio'        : spending_vals_usd['books_supplies']/ max(total_income_usd, 1),
    }

    with st.spinner("Menganalisis kondisi finansial..."):
        status, prob_dict, top_risks = predict(
            input_dict_usd, model, columns, thresholds, class_labels
        )

    meta          = STATUS_META[status]
    sisa_rp       = total_income_rp - total_spending_rp
    ratio_color   = '#2ED573' if balance_ratio > 0.15 else ('#FFA502' if balance_ratio >= 0 else '#FF4757')

    # ── Banner Hasil ──
    st.markdown(f"""
    <div class="fin-card result-{status.lower()}"
         style="display:flex; align-items:center; gap:1.5rem; padding:2rem;">
        <div style="font-size:4rem; line-height:1;">{meta['emoji']}</div>
        <div style="flex:1;">
            <div style="font-size:0.75rem; font-family:'Syne',sans-serif;
                        letter-spacing:0.12em; text-transform:uppercase;
                        color:{meta['color']}; margin-bottom:0.25rem; font-weight:600;">
                Status Kesehatan Finansial
            </div>
            <div style="font-family:'Syne',sans-serif; font-size:2.5rem;
                        font-weight:800; color:{meta['color']}; line-height:1.1;">
                {status}
            </div>
            <div style="color:#9CA3AF; font-size:0.9rem; margin-top:0.4rem;">
                {meta['msg']}
            </div>
        </div>
        <div style="text-align:right;">
            <div style="font-size:0.75rem; color:#6B7280; margin-bottom:0.25rem;">Balance Ratio</div>
            <div style="font-family:'Syne',sans-serif; font-size:2rem;
                        font-weight:700; color:{ratio_color};">
                {balance_ratio:.1%}
            </div>
            <div style="font-size:0.75rem; color:#6B7280; margin-top:0.25rem;">
                {fmt_rp(sisa_rp)} sisa
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Summary Metrics ──
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total Pemasukan",   fmt_rp(total_income_rp))
    m2.metric("Total Pengeluaran", fmt_rp(total_spending_rp),
              delta=f"{fmt_rp(sisa_rp)} sisa", delta_color="normal")
    m3.metric("Balance Ratio", f"{balance_ratio:.1%}")
    m4.metric("Spending/Income", f"{(total_spending_rp/max(total_income_rp,1)):.1%}")

    st.markdown("<br>", unsafe_allow_html=True)

    left, right = st.columns([1.2, 1], gap="large")

    with left:
        st.markdown("""
        <div style="font-family:'Syne',sans-serif; font-size:0.75rem; font-weight:600;
                    letter-spacing:0.12em; text-transform:uppercase; color:#6B7280;
                    margin-bottom:0.75rem;">Distribusi Pengeluaran</div>
        """, unsafe_allow_html=True)

        chart_labels = {
            'housing': 'Kos/Kontrakan', 'food': 'Makan',
            'transportation': 'Transportasi', 'books_supplies': 'Buku & ATK',
            'entertainment': 'Hiburan', 'personal_care': 'Perawatan',
            'technology': 'Teknologi', 'health_wellness': 'Kesehatan',
            'miscellaneous': 'Lain-lain'
        }
        spend_display = {chart_labels[k]: v for k, v in spending_vals_rp.items() if v > 0}
        fig_pie = make_spending_chart(spend_display, total_income_rp)
        st.pyplot(fig_pie, use_container_width=True)
        plt.close()

        st.markdown("<br>", unsafe_allow_html=True)

        st.markdown("""
        <div style="font-family:'Syne',sans-serif; font-size:0.75rem; font-weight:600;
                    letter-spacing:0.12em; text-transform:uppercase; color:#6B7280;
                    margin-bottom:0.75rem;">Probabilitas Prediksi Model</div>
        """, unsafe_allow_html=True)
        fig_prob = make_prob_chart(prob_dict)
        st.pyplot(fig_prob, use_container_width=True)
        plt.close()

    with right:
        st.markdown("""
        <div style="font-family:'Syne',sans-serif; font-size:0.75rem; font-weight:600;
                    letter-spacing:0.12em; text-transform:uppercase; color:#6B7280;
                    margin-bottom:0.75rem;">🔥 Pemicu Risiko Terbesar</div>
        """, unsafe_allow_html=True)

        st.markdown('<div class="fin-card">', unsafe_allow_html=True)
        if len(top_risks) > 0:
            max_score = top_risks.max()
            for feat, score in top_risks.items():
                pct        = int((score / max_score) * 100) if max_score > 0 else 0
                clean_name = feat.replace('_', ' ').title()
                st.markdown(f"""
                <div class="risk-bar-wrap">
                    <div class="risk-label">{clean_name}</div>
                    <div class="risk-bar-bg">
                        <div class="risk-bar-fill" style="width:{pct}%"></div>
                    </div>
                </div>
                """, unsafe_allow_html=True)
        else:
            st.markdown('<div style="color:#6B7280; font-size:0.85rem;">Tidak ada data risiko.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)

        st.markdown("""
        <div style="font-family:'Syne',sans-serif; font-size:0.75rem; font-weight:600;
                    letter-spacing:0.12em; text-transform:uppercase; color:#6B7280;
                    margin-bottom:0.75rem;">💡 Rekomendasi Tindakan</div>
        """, unsafe_allow_html=True)

        st.markdown(f'<div class="fin-card result-{status.lower()}">', unsafe_allow_html=True)
        for i, tip in enumerate(meta['tips'], 1):
            st.markdown(f"""
            <div style="display:flex; gap:0.75rem; margin-bottom:0.75rem; align-items:flex-start;">
                <div style="font-family:'Syne',sans-serif; font-weight:700;
                            color:{meta['color']}; font-size:0.85rem; min-width:1.2rem;">{i}.</div>
                <div style="color:#D1D5DB; font-size:0.87rem; line-height:1.5;">{tip}</div>
            </div>
            """, unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)

        st.markdown("""
        <div style="font-family:'Syne',sans-serif; font-size:0.75rem; font-weight:600;
                    letter-spacing:0.12em; text-transform:uppercase; color:#6B7280;
                    margin-bottom:0.75rem;">📊 Breakdown Pengeluaran</div>
        """, unsafe_allow_html=True)

        st.markdown('<div class="fin-card">', unsafe_allow_html=True)
        sorted_spend = sorted(spending_vals_rp.items(), key=lambda x: x[1], reverse=True)
        for key, val_rp in sorted_spend[:5]:
            if val_rp == 0:
                continue
            pct_of_income = val_rp / max(total_income_rp, 1) * 100
            bar_w = min(int(pct_of_income * 2), 100)
            color = '#FF4757' if pct_of_income > 30 else ('#FFA502' if pct_of_income > 20 else '#4ECDC4')
            label = chart_labels.get(key, key)
            st.markdown(f"""
            <div style="margin-bottom:0.6rem;">
                <div style="display:flex; justify-content:space-between;
                            font-size:0.8rem; margin-bottom:3px;">
                    <span style="color:#D1D5DB;">{label}</span>
                    <span style="color:{color}; font-weight:600;">
                        {fmt_rp(val_rp)}
                        <span style="color:#6B7280; font-weight:400;">({pct_of_income:.0f}%)</span>
                    </span>
                </div>
                <div style="background:#2A2F3E; border-radius:3px; height:5px;">
                    <div style="width:{bar_w}%; background:{color}; height:100%; border-radius:3px;"></div>
                </div>
            </div>
            """, unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)


# ==========================================================================
# FOOTER
# ==========================================================================
st.markdown("<br><br>", unsafe_allow_html=True)
st.markdown("""
<div style="border-top:1px solid #2A2F3E; padding-top:1.5rem; text-align:center;
            color:#6B7280; font-size:0.78rem;">
    AntiKanker DSS · Group 3 · Classification-based Decision Support Systems ·
    Model: Random Forest Classifier
</div>
""", unsafe_allow_html=True)
